
import java.util.ArrayList;
import java.util.HashMap;
import sicut.sqlite.Table;

/**
 *
 * Generated by: S2JConverter
 * at ${date}
 * @author ${user}
 */

public final class ${cap_name} extends Table {
    
    ${variables}

    public ${cap_name}() {
        super();
        tableName = "${name}";
    }
    
    public ${cap_name}(${fields_param}) {
        this();
        ${assign}
    }
    
    ${constructor}
    
    ${list}
    
    public boolean delete() {
        return delete2("${pks_select}");
    }
    
    public boolean update() {
        ${pairs_put}
        return update2("${pks_select}");
    }
    
    public boolean save() {
        ${pairs_put}
        return insert();
    }
    
    ${next_pks}
    
    ${get_set}

}